### ISSUE TITLE
No records in travis_job collection

### ISSUE THREAD

**Issue by shehan** [smartshark/smartshark.github.io#27] opened 2021-12-03 15:34 UTC
I'm using Smartshark version 2.1 (full db)

In my resorted MongoDB, the collection `travis_job` is empty. Furthermore, this collection does not contain the fields mentioned in the [documentation](https://smartshark2.informatik.uni-goettingen.de/documentation/).

Is this an issue with restoring the database or have I downloaded an incorrect version of the db?

**Comment by sherbold** [comment] 2021-12-03 15:52
Thanks for reporting this!

I can confirm this bug in my local copy. I am not sure what went wrong during copying, since my logs say that this collection was copied. As a quick fix, I currently prepare a backup of the travis_job collection from our production server. This might take a couple of days (244 GB data size). Once ready, I will give you a link here. You can then just import this collection into your database. It contains data for more projects than are currently in release 2.1, so you should consider that when using the collection. 

Meanwhile, we try to look for the source of the copy-bug. We are in the last steps of preparing a 2.2 release with about 100 projects and will ensure that the bug is fixed until then.

**Comment by sherbold** [comment] 2021-12-05 13:18
The issue was a missing ['_id'] in a list comprehension for the copy operation, which is [now fixed](https://github.com/smartshark/pycoSHARK/commit/5736914373b01eb772bd20c5f7c1bbf16045eefd).

**Comment by sherbold** [comment] 2021-12-06 15:50
The travis_job collection for the 2.1 release is now ready for download:

http://141.5.100.155/travis_job.bson.gz
http://141.5.100.155/travis_job.metadata.json.gz

You can just load this into your database with the mongorestore command.

**Comment by sherbold** [comment] 2022-01-11 09:24
I assume the problem is resolved. Please reopen if there are additional problems.

**Closed by sherbold** 2022-01-11 09:24 UTC
